sudo: required
services:
  - docker

before_install:
  - docker build -t haitran99/react -f Dockerfile.dev .

script:
  # Bydefault Test doesn't exit. Addon to automatically exit
  - docker run -e CI=true haitran99/react npm run test
